### ISSUE TITLE
厚脸请求 编译好的appimage添加fcitx5支持

### ISSUE THREAD

**Issue by Cosson2017** [tamlok/vnote#657]
OS Version (操作系统):  Linux,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3,  d78e892d5cc  etc..

Symptoms (表现):不能试用fcitx5

How to Repro (如何复现):

大大你好：本人arch，qt5.12,编译出来的二进制read mode有问题，所以厚脸请求 能否在appimage添加fcitx5支持

**Comment by Cosson2017** [comment]
> OS Version (操作系统): Linux,
> 
> VNote Version (Help - About VNote - Version: )(VNote版本): 2.3, [d78e892](https://github.com/tamlok/vnote/commit/d78e892d5ccfcb1a096cec678adb556d5d2a4fb8) etc..
> 
> Symptoms (表现):不能试用fcitx5
> 
> How to Repro (如何复现):
> 
> 大大你好：本人arch，qt5.12,编译出来的二进制read mode有问题，所以厚脸请求 能否在appimage添加fcitx5支持

**Comment by Cosson2017** [comment]
#258

**Comment by tamlok** [comment]
Hi,

AppImage是有fcitx的支持的，是在Arch上用不了fcitx输入中文吗？

另外，是2.3才有这个问题，还是之前2.2也有？

我后面会适配5.12，这样方便大家自行编译。

谢谢！

**Comment by Cosson2017** [comment]
2.2也有这个问题，fctix是可以正常使用的，fcitx5还不能使用。

**Comment by tamlok** [comment]
Fcitx5是最新出的吗？您参考一下这个CI脚本，VNote应该是自行编译了1.0.5版本的fcitx：

https://github.com/tamlok/vnote/blob/470a40c80b96e6fa15048f4a95fce60f31017fce/.travis_linux.sh#L18

不知道是不是和fcitx5不一样。

实在不行，我过几天看看怎么把vnote兼容5.12吧，这时候arch用户就可以随心所欲了。

**Comment by Cosson2017** [comment]
fcitx5是和fcitx不一样。
![image](https://user-images.githubusercontent.com/20379044/53851910-1dc06500-3ffb-11e9-83d2-ffc8d0473b59.png) 有个专门的fcitx5 qt输入法插件

**Comment by tamlok** [comment]
Hi,

I tried but [failed](https://travis-ci.org/tamlok/vnote/jobs/502552920). Do you know how to build `fcitx5` in Ubuntu 14.04?

**Comment by tamlok** [comment]
BTW, now `master` branch should work with Qt 5.12. You could now use `vnote-git` in AUR.

**Comment by Cosson2017** [comment]
非常感谢大大的工作

**Comment by zzndb** [comment]
> now `master` branch should work with Qt 5.12.

今天打包的时候发现，自带的5.12编译出来也貌似没啥问题了，如果真是这样的话，建议大大修改一下[编译文档](https://tamlok.github.io/vnote/en_us/#!docs/Developers/Build%20VNote.md)。

**Comment by tamlok** [comment]
@zzndb 之前修复了5.12的问题。不过好像样式在5.12上面和5.9不太一样。我后面修改一下文档。谢谢！

**Comment by heyizhang** [comment]
俺也想厚着脸皮求大大们，能不能给个 arch 上支持 fcitx5 的包呀？




> 非常感谢大大的工作

**Comment by tamlok** [comment]
@heyizhang Arch上面请下载官网提供的AppImage，或者AUR的`vnote-bin`，其他源的可能会有各种Qt的版本问题。

**Comment by heyizhang** [comment]
> @heyizhang Arch上面请下载官网提供的AppImage，或者AUR的`vnote-bin`，其他源的可能会有各种Qt的版本问题。

我使用的 vnote release 里面提供 appimage. 然后，用 fcitx5 也不能在 vnote 里面输入中文。
其他地方都可以呢emm

**Comment by tamlok** [comment]
@heyizhang ~~这就比较头疼了，方法可能只能下载Qt 5.9，然后在本地机器上面编译了~~Linux下面的fcitx和Qt一直都是一个头疼的问题~

**Comment by heyizhang** [comment]
这样啊，。。，那我去试试。谢谢大大了

**Comment by heyizhang** [comment]
那啥， 大大，自己编译的时候，这里有个报错：Error compiling js file: ../../vnote.git/src/utils/mermaid/mermaid.min.js:31:453012: error: Identifier o has already been declared。

**Comment by heyizhang** [comment]
因为习惯 qt creator ，然后使用它 编译还报错来着emm, 但是使用编译文档的 linux 的命令的方式就好了。
终于可以愉快的输入中文了，谢谢大大
